### ISSUE TITLE
VwmOpen isn't working

### ISSUE THREAD

**Issue by RossComputerGuy** [paroxayte/vwm.vim#1]
Running `:VwmOpen` causes this error:
```
Error detected while processing function vwm#open[1]..<SNR>49_lookup_node:
line    2:
E121: Undefined variable: g:vwm#layouts
E15: Invalid expression: g:vwm#layouts
line    9:
top not in list of root nodes
```

**Comment by fireflowerr** [comment]
Did you define g:vwm#layouts somewhere? You have to define layouts before you can can open them.If you have defined it, could you post the variable definition here?

**Comment by RossComputerGuy** [comment]
I though the variable wasn't required to be defined. Maybe having a default set of layouts is a good idea.

**Comment by paroxayte** [comment]
Hmm. I will consider it. This plugin doesn't fill the buffers with anything by default. I think there may be some complications adding something like a default layout with bifurcated terminal panel at the bottom. The API is different between vim and nvim. Still, I will consider it.

**Comment by fireflowerr** [comment]
Hmm. I will consider it. This plugin doesn't fill the buffers with anything by default. I think there may be some complications adding something like a default layout with bifurcated terminal panel at the bottom. The API is different between vim and nvim. Still, I will consider it.
