### ISSUE TITLE
please add configure example in readme. I find configure from commit history and vim script. It is not friendly.

### ISSUE THREAD

**Issue by zhoupro** [paroxayte/vwm.vim#5]
`let s:bot = {
      \    'name': 'bot',
      \    'set_all': ['nonu', 'nornu'],
      \    'bot':
      \    {
      \      'h_sz': 12,
      \      'init': [ 'term zsh' ]
      \    }
      \  }

let g:vwm#layouts = [s:bot]`

**Comment by fireflowerr** [comment]
I will add a link to the default config. However, you could find the default config with `:echo g:vwm#layouts[0]` as long as it hasn't been overridden in your config.
